// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng/core-proxy/services/proto/api.proto

package dongfeng_svc_core_proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthcheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthcheckRequest) Reset()         { *m = HealthcheckRequest{} }
func (m *HealthcheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthcheckRequest) ProtoMessage()    {}
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{0}
}
func (m *HealthcheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthcheckRequest.Unmarshal(m, b)
}
func (m *HealthcheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthcheckRequest.Marshal(b, m, deterministic)
}
func (dst *HealthcheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckRequest.Merge(dst, src)
}
func (m *HealthcheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthcheckRequest.Size(m)
}
func (m *HealthcheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckRequest proto.InternalMessageInfo

type HealthcheckResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthcheckResponse) Reset()         { *m = HealthcheckResponse{} }
func (m *HealthcheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthcheckResponse) ProtoMessage()    {}
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{1}
}
func (m *HealthcheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthcheckResponse.Unmarshal(m, b)
}
func (m *HealthcheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthcheckResponse.Marshal(b, m, deterministic)
}
func (dst *HealthcheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckResponse.Merge(dst, src)
}
func (m *HealthcheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthcheckResponse.Size(m)
}
func (m *HealthcheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckResponse proto.InternalMessageInfo

func (m *HealthcheckResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type LoginResponse struct {
	Version              string       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	User                 *UserProfile `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SystemBroadcasting   []*Operation `protobuf:"bytes,3,rep,name=system_broadcasting,json=systemBroadcasting,proto3" json:"system_broadcasting,omitempty"`
	UserUpdates          []*Operation `protobuf:"bytes,4,rep,name=user_updates,json=userUpdates,proto3" json:"user_updates,omitempty"`
	FriendUpdates        []*Operation `protobuf:"bytes,5,rep,name=friend_updates,json=friendUpdates,proto3" json:"friend_updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginResponse) GetUser() *UserProfile {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetSystemBroadcasting() []*Operation {
	if m != nil {
		return m.SystemBroadcasting
	}
	return nil
}

func (m *LoginResponse) GetUserUpdates() []*Operation {
	if m != nil {
		return m.UserUpdates
	}
	return nil
}

func (m *LoginResponse) GetFriendUpdates() []*Operation {
	if m != nil {
		return m.FriendUpdates
	}
	return nil
}

// UserProfile user profile
type UserProfile struct {
	Newuser              bool       `protobuf:"varint,1,opt,name=newuser,proto3" json:"newuser,omitempty"`
	Admin                bool       `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Id                   int64      `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Email                string     `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string     `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string     `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Settings             []*Setting `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{4}
}
func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (dst *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(dst, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetNewuser() bool {
	if m != nil {
		return m.Newuser
	}
	return false
}

func (m *UserProfile) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *UserProfile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserProfile) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

// Setting user setting
type Setting struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{5}
}
func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (dst *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(dst, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Setting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Setting) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type Operation struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Operation            string   `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c51e1629f48e2d94, []int{6}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Operation) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Operation) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Operation) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthcheckRequest)(nil), "dongfeng.svc.core.proxy.HealthcheckRequest")
	proto.RegisterType((*HealthcheckResponse)(nil), "dongfeng.svc.core.proxy.HealthcheckResponse")
	proto.RegisterType((*LoginRequest)(nil), "dongfeng.svc.core.proxy.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "dongfeng.svc.core.proxy.LoginResponse")
	proto.RegisterType((*UserProfile)(nil), "dongfeng.svc.core.proxy.UserProfile")
	proto.RegisterType((*Setting)(nil), "dongfeng.svc.core.proxy.Setting")
	proto.RegisterType((*Operation)(nil), "dongfeng.svc.core.proxy.Operation")
}

func init() {
	proto.RegisterFile("github.com/ilovelili/dongfeng/core-proxy/services/proto/api.proto", fileDescriptor_api_c51e1629f48e2d94)
}

var fileDescriptor_api_c51e1629f48e2d94 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x4d, 0x7f, 0x77, 0x7a, 0xd7, 0x87, 0xb9, 0xc3, 0x0b, 0xc5, 0x87, 0x12, 0x54, 0x0a,
	0x6a, 0x02, 0xf5, 0xc5, 0x07, 0x5f, 0x14, 0x44, 0x0f, 0x04, 0x65, 0x8f, 0x03, 0xdf, 0x8e, 0x6d,
	0x32, 0x4d, 0x57, 0x93, 0xdd, 0xb8, 0xbb, 0xad, 0xf6, 0x5f, 0x54, 0xfc, 0x9f, 0x24, 0x9b, 0xa4,
	0xad, 0x48, 0xb9, 0xbe, 0xed, 0x77, 0x98, 0xcf, 0x97, 0x99, 0x6f, 0x98, 0xc0, 0x9b, 0x54, 0xd8,
	0xd5, 0x7a, 0x11, 0xc6, 0x2a, 0x8f, 0x44, 0xa6, 0x36, 0x94, 0x89, 0x4c, 0x44, 0x89, 0x92, 0xe9,
	0x92, 0x64, 0x1a, 0xc5, 0x4a, 0xd3, 0x8b, 0x42, 0xab, 0x9f, 0xdb, 0xc8, 0x90, 0xde, 0x88, 0x98,
	0x4c, 0x54, 0x68, 0x65, 0x55, 0xc4, 0x0b, 0x11, 0xba, 0x17, 0x5e, 0x35, 0xdd, 0xa1, 0xd9, 0xc4,
	0x61, 0x49, 0x84, 0x8e, 0x08, 0x2e, 0x01, 0x3f, 0x10, 0xcf, 0xec, 0x2a, 0x5e, 0x51, 0xfc, 0x8d,
	0xd1, 0xf7, 0x35, 0x19, 0x1b, 0x44, 0x70, 0xf1, 0x4f, 0xd5, 0x14, 0x4a, 0x1a, 0x42, 0x1f, 0xfa,
	0x39, 0x19, 0xc3, 0x53, 0xf2, 0xbd, 0xa9, 0x37, 0x1b, 0xb2, 0x46, 0x06, 0x63, 0x38, 0xfb, 0xa8,
	0x52, 0x21, 0x1b, 0x83, 0x5f, 0x2d, 0x38, 0xaf, 0x0b, 0x7b, 0x76, 0x43, 0xda, 0x08, 0x25, 0x1b,
	0xb6, 0x96, 0xf8, 0x0a, 0x3a, 0x6b, 0x43, 0xda, 0x6f, 0x4d, 0xbd, 0xd9, 0x68, 0xfe, 0x38, 0x3c,
	0x32, 0x6a, 0x78, 0x6b, 0x48, 0x7f, 0xd6, 0x6a, 0x29, 0x32, 0x62, 0x8e, 0xc0, 0x1b, 0xb8, 0x30,
	0x5b, 0x63, 0x29, 0xbf, 0x5b, 0x68, 0xc5, 0x93, 0x98, 0x1b, 0x2b, 0x64, 0xea, 0xb7, 0xa7, 0xed,
	0xd9, 0x68, 0x1e, 0x1c, 0x35, 0xfa, 0x54, 0x90, 0xe6, 0x56, 0x28, 0xc9, 0xb0, 0xc2, 0xdf, 0x1e,
	0xd0, 0xf8, 0x0e, 0xce, 0x4a, 0xf3, 0xbb, 0x75, 0x91, 0x70, 0x4b, 0xc6, 0xef, 0x9c, 0xec, 0x36,
	0x2a, 0xb9, 0xdb, 0x0a, 0xc3, 0x6b, 0x18, 0x2f, 0xb5, 0x20, 0x99, 0xec, 0x8c, 0xba, 0x27, 0x1b,
	0x9d, 0x57, 0x64, 0x6d, 0x15, 0xfc, 0xf1, 0x60, 0x74, 0xb0, 0x7c, 0x19, 0xa5, 0xa4, 0x1f, 0x2e,
	0xb3, 0x32, 0xca, 0x01, 0x6b, 0x24, 0x5e, 0x42, 0x97, 0x27, 0xb9, 0x90, 0x2e, 0xcb, 0x01, 0xab,
	0x04, 0x8e, 0xa1, 0x25, 0x12, 0xbf, 0x3d, 0xf5, 0x66, 0x6d, 0xd6, 0x12, 0x49, 0xd9, 0x45, 0x39,
	0x17, 0x99, 0xdf, 0x71, 0x1f, 0xa2, 0x12, 0x88, 0xd0, 0x91, 0x3c, 0x27, 0xbf, 0xeb, 0x8a, 0xee,
	0x8d, 0x0f, 0xa1, 0xc7, 0x37, 0xdc, 0x72, 0xed, 0xf7, 0x5c, 0xb5, 0x56, 0xf8, 0x1a, 0x06, 0x86,
	0x6c, 0x19, 0x97, 0xf1, 0xfb, 0x6e, 0xad, 0xe9, 0xd1, 0xb5, 0x6e, 0xaa, 0x46, 0xb6, 0x23, 0x82,
	0xf7, 0xd0, 0xaf, 0x8b, 0xf5, 0x68, 0xde, 0x6e, 0xb4, 0x66, 0x88, 0xd6, 0xc1, 0x10, 0x3e, 0xf4,
	0x49, 0xf2, 0x45, 0x46, 0xd5, 0x0e, 0x03, 0xd6, 0xc8, 0x40, 0xc3, 0x70, 0x17, 0x1a, 0x5e, 0x41,
	0xdf, 0x7d, 0xb7, 0xda, 0x6f, 0xc8, 0x7a, 0xa5, 0xbc, 0x76, 0x9e, 0x56, 0xec, 0x3d, 0xcb, 0x37,
	0x3e, 0x82, 0xa1, 0x6a, 0x48, 0xe7, 0x3a, 0x64, 0xfb, 0x02, 0x4e, 0x60, 0x10, 0x73, 0x4b, 0xa9,
	0xd2, 0xdb, 0x3a, 0xa3, 0x9d, 0x9e, 0xff, 0xf6, 0xa0, 0xcd, 0x0b, 0x81, 0x5f, 0x61, 0x74, 0x70,
	0x22, 0xf8, 0xec, 0xe8, 0xfe, 0xff, 0x9f, 0xd7, 0xe4, 0xf9, 0x69, 0xcd, 0xd5, 0xe5, 0x04, 0x0f,
	0xf0, 0x0b, 0x74, 0xdd, 0x31, 0xe1, 0x93, 0xa3, 0xe0, 0xe1, 0xf5, 0x4d, 0x9e, 0xde, 0xd7, 0xd6,
	0x38, 0x2f, 0x7a, 0xee, 0xf7, 0xf0, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xe1, 0x0a,
	0x1c, 0x63, 0x04, 0x00, 0x00,
}
