apiVersion: v1
kind: Service
metadata:
  labels:
    service: dongfeng-core-proxy
  namespace: dongfeng-back
  name: dongfeng-core-proxy
spec:
  type: NodePort
  ports:
  - name: api-port
    port: 80
    targetPort: "api-port"
    protocol: TCP
  selector:    
      app: dongfeng-core-proxy