apiVersion: v1
kind: Service
metadata:
  labels:
    service: dongfeng-core-proxy
  namespace: dongfeng-back
  name: dongfeng-core-proxy
spec:
  type: LoadBalancer
  ports:
  - name: api-port
    port: 8080
    targetPort: "api-port"
    protocol: TCP
  selector:
    app: dongfeng-core-proxy