apiVersion: v1
kind: Service
metadata:
  labels:
    service: dongfeng-core-proxy
  namespace: dongfeng-back
  name: dongfeng-core-proxy
spec:
  # https://stackoverflow.com/questions/35884643/kubernetes-external-load-balancer-service-on-digitalocean
  # We can create a nginx ingress controller
  clusterIP: None
  ports:
  - name: headless
    port: 55551
    targetPort: 0
  selector:    
    app: dongfeng-core-proxy