apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    deployment: dongfeng-core-proxy
  namespace: dongfeng-back
  name: dongfeng-core-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dongfeng-core-proxy
  template:
    metadata:      
      labels:
        app: dongfeng-core-proxy
    spec:      
      containers:
      - name: dongfeng-core-proxy        
        image: ilovelili/dongfeng-core-proxy:latest
        imagePullPolicy: Always
        command: [
          "./server",
        ]
        env:
        - name: MICRO_REGISTRY
          value: kubernetes
        - name: MH_ENVIROMENT
          value: dev
        - name: MICRO_SERVER_ADDRESS
          value: 0.0.0.0:9091
        ports:
          - containerPort: 9091
      - name: liveness
        command: [
          "/health",
          "--health_address=0.0.0.0:8080",
          "--server_name=dongfeng.svc.core.server.api",
          "--server_address=0.0.0.0:9091",
        ]
        image: ilovelili/micro-health:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3